#!python

# create 26 folders in packages/index , each name is from a to z

import os
import shutil


def create_index():
    for i in range(26):
        folder = chr(ord('a') + i)
        if not os.path.exists("packages/index/"+folder):
            os.makedirs("packages/index/"+folder)


create_index()
